

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Third Test",
  "author": "Test Blogger",
  "url": "www.blogtest.com",
  "likes": 0
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "dennism",
  "name": "Dennis Magnusson",
  "password": "passthis"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "de",
  "name": "Dennis Magnusson",
  "password": "passthis"
}
