

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbm5pc20iLCJpZCI6IjYyY2VjYzRjMWI4NDcxODNlMmUwMTM5ZCIsImlhdCI6MTY1NzcyMDI2M30.k-MYbvZdlcGHy_8fzUD3z3t0O52Z2iQBB-k-zIbV8us

{
  "title": "First Test",
  "author": "Test Blogger",
  "url": "www.blogtest.com",
  "likes": 0
}

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Third Test",
  "author": "Test Blogger",
  "url": "www.blogtest.com",
  "likes": 0
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "rootword"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "dennism",
  "name": "Dennis Magnusson",
  "password": "passthis"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "dennism",
  "password": "passthis"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "de",
  "name": "Dennis Magnusson",
  "password": "passthis"
}

###

DELETE http://localhost:3003/api/blogs/62ceb424a9b1daf5a093cf19
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbm5pc20iLCJpZCI6IjYyY2ViM2UyYTliMWRhZjVhMDkzY2YwZSIsImlhdCI6MTY1NzcxNjA5NX0.4zTdasU1m8AxxteohRCwyeRzMB4j3GrmKO_BRjYWFB4


